# Generated by Django 3.2.3 on 2021-06-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_attendanceclass_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerange',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='attendancerange',
            old_name='start_date',
            new_name='start',
        ),
    ]
