# Generated by Django 3.2.3 on 2021-06-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20210602_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerange',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='attendancerange',
            old_name='start',
            new_name='start_date',
        ),
    ]
