# Generated by Django 3.2.3 on 2021-06-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20210614_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='sem',
            new_name='level',
        ),
    ]
