# Generated by Django 3.2.4 on 2021-06-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_rename_sem_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(choices=[('ضعيف', 'ضعيف'), ('مقبول', 'مقبول'), ('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('امتياز', 'امتياز')], default='امتياز', max_length=7)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
