# Generated by Django 3.0.6 on 2021-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_finalresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
